export const counterSlice = (set) => ({
	counter: 0,
	activeGame: null,
	isEnd: false,
	gamesCount: 0,
	categoryGamesCount: 0,
	setGamesCount: (num) => set(() => ({ gamesCount: num })),
	setCategoryGamesCount: (num) => set(() => ({ categoryGamesCount: num })),
	setIsEnd: (bool) => set(() => ({ isEnd: bool })),
	setActiveGame: (game) => set(() => ({ activeGame: game })),
	setCounter: (count) => set(() => ({ counter: count })),
	increaseCounter: () => set((state) => ({ counter: state.counter + 1 })),
	emptyCounter: () => set(() => ({ counter: 0 })),
	decreaseCounter: () => set((state) => ({ counter: state.counter - 1 })),
	setDirection: (direction) => set({ direction }),
	direction: 'down',
});
