export const layoutSlice = set => ({
   categoriesHeight: undefined,
   loading: true,
   XsIsOpen: false,
   categoryBottomSheetIsOpen: false,
   gameInfoBottomSheetIsOpen: false,
   searchBottomSheetIsOpen: false,
   basketBottomSheet: false,
   XsGameName: '',
   productAddToCardIsVisiible: false,
   countButtonUpIsShown: false,
   XsText: '',
   queriesCompleted: 0,
   isGamePass: false,
   categoryBottomSheetObj: {},
   activeSeries: {},
   isFromHomeSale: false,
   isFromGamePass: false,
   isNewAccOpen: false,
   microsoftModalIsOpen: false,
   isOldAcc: false,
   isSaleUrl: false,
   isOldAccOpen: false,
   XsTitle: 'Подсказка',
   isNewAcc: false,
   setIsNewAccOpen: bool => set(() => ({ isNewAccOpen: bool })),
   setIsOldAccOpen: bool => set(() => ({ isOldAccOpen: bool })),
   setIsOldAcc: bool => set(() => ({ isOldAcc: bool })),
   setIsNewAcc: bool => set(() => ({ isNewAcc: bool })),
   setMicrosoftModalIsOpen: bool => set(() => ({ microsoftModalIsOpen: bool })),
   setActiveSeries: obj => set(() => ({ activeSeries: obj })),
   setCategoryBottomSheetObj: obj => set(() => ({ categoryBottomSheetObj: obj })),
   setCategoriesHeight: height => set(() => ({ categoriesHeight: height })),
   setIsFromGamePass: val => set(() => ({ isFromGamePass: val })),
   setLoading: loading => set(() => ({ loading })),
   setIsFromHomeSale: val => set(() => ({ isFromHomeSale: val })),
   setXsText: text => set(() => ({ XsText: text })),
   setXsTitle: title => set(() => ({ XsTitle: title })),
   setIsGamePass: val => set(() => ({ isGamePass: val })),
   changeXsIsOpen: bool => set(() => ({ XsIsOpen: bool })),
   closeXsIsOpen: () => set(() => ({ XsIsOpen: false })),
   setQueriesCompleted: count => set(st => ({ queriesCompleted: (count || st.queriesCompleted + 1) })),
   setCategoryBottomSheetIsOpen: bool =>
      set(() => ({ categoryBottomSheetIsOpen: bool })),
   setGameInfoBottomSheetIsOpen: bool =>
      set(() => ({ gameInfoBottomSheetIsOpen: bool })),
   setSearchBottomSheetIsOpen: bool =>
      set(() => ({ searchBottomSheetIsOpen: bool })),
   setBasketBottomSheet: bool => set(() => ({ basketBottomSheet: bool })),
   setXsGameName: name => set(() => ({ XsGameName: name })),
   setProductAddToCardIsVisiible: bool =>
      set(() => ({ productAddToCardIsVisiible: bool })),
   setCountButtonUpIsShown: bool => set(() => ({ countButtonUpIsShown: bool })),
   setIsSaleUrl: bool => set(() => ({ isSaleUrl: bool })),
});
